version: '2.0'
volumes:
    data-vol: # Volume to host db service data locally.
      driver: local
    php_dependencies: # Volume to cache vendor locally.
      driver: local
    npm_dependencies: # Volume to cache node_modules locally.
      driver: local
services:
  proxy-app:
    build:
      context: ./
      dockerfile: dockers/Dockerfile
      args:
        BASE_TAG: latest
        IMAGE_NAME: boilerplate/proxy-php-base-local
        ENV: local
        PORT: 80
    volumes:
      - ./:/var/www
      - ./environments/.env.local:/var/www/.env
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./dockers/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
      # To avoid syncing the vendor directory
      - php_dependencies:/var/www/vendor
      - npm_dependencies:/var/www/node_modules
    ports:
      - "80:80"
    links:
      - dbmaster
      - dbslave
      - redis
    container_name: boilerplate-proxy-php-cont
  dbmaster:
    image: boilerplate/db-local:latest
    restart: always
    ports:
        - "5432:5432" # host:container
    volumes:
      - data-vol:/bitnami/postgresql
      - ./database/slave-entrypoint.sh:/docker-entrypoint-initdb.d/slave-entrypoint.sh
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=master
      - POSTGRESQL_PASSWORD=master
      - POSTGRESQL_DATABASE=forge
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: boilerplate-master-db-cont
  dbslave:
    image: boilerplate/db-local:latest
    restart: always
    ports:
        - "5433:5432" # rep:container
    depends_on:
      - dbmaster
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=dbmaster
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
    container_name: boilerplate-slave-db-cont
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
    volumes:
     - $PWD/redis-data:/var/lib/redis
    environment:
     - REDIS_REPLICATION_MODE=master
    container_name: boilerplate-cache-cont
